"""add cascade properties to tool agent id

Revision ID: 660c5d669b81
Revises: a47415c8d471
Create Date: 2026-04-01 16:09:57.280210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '660c5d669b81'
down_revision: Union[str, Sequence[str], None] = 'a47415c8d471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('position', sa.Uuid(), nullable=True))
    op.add_column('tool', sa.Column('config', sa.Uuid(), nullable=True))
    op.alter_column('tool', 'agent_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('tool_agent_id_fkey'), 'tool', type_='foreignkey')
    op.create_foreign_key(None, 'tool', 'agent', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tool', 'positionnode', ['position'], ['id'])
    op.create_foreign_key(None, 'tool', 'nodeconfig', ['config'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.create_foreign_key(op.f('tool_agent_id_fkey'), 'tool', 'agent', ['agent_id'], ['id'])
    op.alter_column('tool', 'agent_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('tool', 'config')
    op.drop_column('tool', 'position')
    # ### end Alembic commands ###
